

services:
  go-survey-bot:
    build: 
      context: ./
      dockerfile: Dockerfile

    env_file: .env
    environment:
      GOOGLE_CREDENTIALS_FILE: "/google/credentials.json"
    volumes:
      - ./google:/google
